import { TProduct } from "../types/TProduct";
const productAPI: Array<TProduct> = [
  {
    id: 1,
    img: "",
    name: "Iphone 15 Promax (256Gb)",
    price: 28790000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "Dien thoai - tablet",
    brand: "Apple",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 2,
    img: "",
    name: "Samsung Galaxy S24 Plus - 12GB/256GB ",
    price: 2500000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "Dien thoai - tablet",
    brand: "Samsung",
    origin: "Hàn Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 3,
    img: "",
    name: "Điện Thoại Di Động Mobell M539 4G - Chính hãng",
    price: 640000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: false,
    category: "Dien thoai - tablet",
    brand: "Mobell",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 4,
    img: "",
    name: "realme C60 4GB/64GB - Chính hãng",
    price: 2500000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "Dien thoai - tablet",
    brand: "Oppo",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 5,
    img: "",
    name: "Nubia Neo 2 8GB+12GB/256GB - Chính hãng",
    price: 4500000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: false,
    category: "Dien thoai - tablet",
    brand: "ZTE",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 6,
    img: "",
    name: "iPhone 11 (64GB) - Chính hãng",
    price: 7500000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: true,
    category: "Dien thoai - tablet",
    brand: "Apple",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 7,
    img: "",
    name: "HONOR X7b - 8GB/256GB - Chính hãng",
    price: 5290000,
    discount: false,
    discountType: "",
    bestSelling: false,
    category: "Dien thoai - tablet",
    brand: "Huawei",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 8,
    img: "",
    name: "Samsung Galaxy A55 - 8GB/128GB - Chính hãng",
    price: 8200000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "Dien thoai - tablet",
    brand: "Samsung",
    origin: "Hàn Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 9,
    img: "",
    name: "iPad Pro M4 13 Wifi (256GB) - Chính hãng Apple VN",
    price: 37990000,
    discount: false,
    discountType: "",
    bestSelling: true,
    category: "Dien thoai - tablet",
    brand: "Aplle",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 10,
    img: "",
    name: "Samsung Galaxy Tab A9 Plus Wifi 8GB/128GB - Chính hãng",
    price: 5190000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: false,
    category: "Dien thoai - tablet",
    brand: "Samsung",
    origin: "Hàn Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 11,
    img: "",
    name: "Laptop Asus Vivobook M1605YA-MB303W - Chính hãng",
    price: 1850000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: false,
    category: "Laptop",
    brand: "Asus",
    origin: "Đài Loan",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 12,
    img: "",
    name: "Laptop Lenovo Ideapad Slim 5 14IMH9 83DA001NVN - Chính hãng",
    price: 22000000,
    discount: false,
    discountType: "",
    bestSelling: true,
    category: "Laptop",
    brand: "Lenovo",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 13,
    img: "",
    name: "Laptop Dell Inspiron 3530 N5I5007W1 - Chính hãng",
    price: 17500000,
    discount: false,
    discountType: "",
    bestSelling: true,
    category: "Laptop",
    brand: "Dell",
    origin: "TRung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 14,
    img: "",
    name: "Laptop ASUS Vivobook 14 X1404ZA-NK389W - Chính hãng",
    price: 1800000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: false,
    category: "Laptop",
    brand: "Asus",
    origin: "Đài Loan",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 15,
    img: "",
    name: "Laptop ASUS Zenbook 14 OLED UX3405MA-PP588W - Chính hãng",
    price: 26000000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: false,
    category: "Laptop",
    brand: "Asus",
    origin: "Hàn Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 16,
    img: "",
    name: "Laptop MSI Cyborg 15 AI A1VE-053VN - Chính hãng",
    price: 30000000,
    discount: false,
    discountType: "",
    bestSelling: true,
    category: "Laptop",
    brand: "MSI",
    origin: "Đài Loan",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 17,
    img: "",
    name: "Laptop Dell Inspiron 15 3520 (71027003) - Chính hãng",
    price: 17000000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "laptop",
    brand: "Dell",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 18,
    img: "",
    name: "Laptop Gaming Acer Nitro V - ANV15-51-58AN - Chính hãng",
    price: 2000000,
    discount: false,
    discountType: "",
    bestSelling: true,
    category: "Laptop",
    brand: "Acer",
    origin: "Đài loan",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 19,
    img: "",
    name: "Laptop Lenovo LOQ 15IRH8 (82XV00QXVN) - Chính hãng",
    price: 32000000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: false,
    category: "Laptop",
    brand: "Lenovo",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 20,
    img: "",
    name: "Laptop HUAWEI MateBook 14 2022 - Chính hãng",
    price: 25000000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: false,
    category: "Laptop",
    brand: "Huawei",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 21,
    img: "",
    name: "TV Samsung Neo QLED QA55QN85AAKXXV (4K/55-inch) - Chính hãng",
    price: 50000000,
    discount: true,
    discountType: "Giam gia 50%",
    bestSelling: false,
    category: "Smart home",
    brand: "Samsung",
    origin: "Hàn Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 22,
    img: "",
    name: "TV TOSHIBA 65C350LP (4K/65-inch) - Chính hãng",
    price: 23000000,
    discount: false,
    discountType: "",
    bestSelling: true,
    category: "Smart home",
    brand: "Toshiba",
    origin: "Nhật bản",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 23,
    img: "",
    name: "TV Casper 32HGS610 (HD/32-inch) - Chính hãng",
    price: 6000000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: true,
    category: "Smart home",
    brand: "Casper",
    origin: "Thái Lan",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 24,
    img: "",
    name: "Robot hút bụi Xiaomi Vacuum X20 - Chính hãng",
    price: 1000000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: false,
    category: "Smart home",
    brand: "Xiaomi",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 25,
    img: "",
    name: "Máy chiếu mini Beecube X2 Max Gen 4 Full HD 1080P - Chính Hãng",
    price: 4000000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "",
    brand: "",
    origin: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 26,
    img: "",
    name: "Máy lọc không khí Xiaomi Air Purifier 4 - Chính hãng",
    price: 5000000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: false,
    category: "Smart home",
    brand: "Xiaomi",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 27,
    img: "",
    name: "Camera IP Wi-Fi TP-Link Tapo C210 360° 3MP - Chính hãng",
    price: 1500000,
    discount: true,
    discountType: "Giam gia 50%",
    bestSelling: true,
    category: "Smart home",
    brand: "TP-Link",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 28,
    img: "",
    name: "Máy in phun đa chức năng Brother DCP-T420W ",
    price: 5000000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: false,
    category: "Do dung van phong",
    brand: "Brother",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 29,
    img: "",
    name: "Điện thoại IP Grandstream GRP2601",
    price: 14000000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "Do dung van phong",
    brand: "IP",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 30,
    img: "",
    name: "Máy chấm công bằng thẻ cảm ứng KOBIO SC700",
    price: 2000000,
    discount: true,
    discountType: "Giam gia 50%",
    bestSelling: true,
    category: "Do dung van phong",
    brand: "KOBIO",
    origin: "Hàn Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 31,
    img: "",
    name: "Ghế Công Thái Học B-103",
    price: 6000000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: true,
    category: "Do dung van phong",
    brand: "Ergonomic",
    origin: "Đức",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 32,
    img: "",
    name: "Ghế chơi game đa chức năng tự động Ingrem GUNDAM DXracer Gaming",
    price: 150000000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: false,
    category: "Gaming",
    brand: "Ingrem",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 33,
    img: "",
    name: "Chuột Logitech G502 HERO",
    price: 1000000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: true,
    category: "Gaming",
    brand: "Logitech",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 34,
    img: "",
    name: "Bàn phím cơ DarkFlash GD100 Milky Brown Yellow Axis switch - Hàng Giá",
    price: 900000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "Gaming",
    brand: "Asus",
    origin: "hàn Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 35,
    img: "",
    name: "Túi đựng kính VR LTGEM EVA cho Oculus Rift + Touch Virtual Reality",
    price: 1000000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: false,
    category: "Gaming",
    brand: "EVA",
    origin: "Nhật bản",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 36,
    img: "",
    name: "Đồng hồ thông minh KIESLECT LORA 2 - Chính Hãng",
    price: 1700000,
    discount: true,
    discountType: "Giam gia 50%",
    bestSelling: false,
    category: "Phụ kiện",
    brand: "KIESLECT",
    origin: "Hàn Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 37,
    img: "",
    name: "Đồng hồ thông minh Garmin Forerunner 165 Music - Chính Hãng",
    price: 8000000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: true,
    category: "Phụ kiện",
    brand: "Fore Runner",
    origin: "Anh",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 38,
    img: "",
    name: "Router WiFi 6 TP-Link Archer AX12 - Chính hãng",
    price: 1500000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "Phụ kiện",
    brand: "TP-Link",
    origin: "Trung Quốc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 39,
    img: "",
    name: "Sạc dự phòng Energizer 5,000mAh /3.7V Li-Polymer - QM5000 - Chính Hãng",
    price: 750000,
    discount: true,
    discountType: "Giam gia 25%",
    bestSelling: true,
    category: "Phụ kiện",
    brand: "Energizer",
    origin: "Mỹ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 40,
    img: "",
    name: "Củ sạc Baseus Compact Charger 3U 17W CN - Chính hãng",
    price: 500000,
    discount: true,
    discountType: "Giam gia 10%",
    bestSelling: true,
    category: "Phụ kiện",
    brand: "Baseus",
    origin: "Úc",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];
export default productAPI;
